/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import form.product.FormProduct;
import controller.Controller;
import domain.RedemptionBill;
import domain.User;
import form.manufacturer.FormManufacturer;
import form.manufacturer.FormSearchManufacturer;
import form.product.FormSearchProduct;
import form.product.storage.FormProductStorage;
import form.redemptionbill.FormRedemptionBill;
import form.redemptionbill.FormRedemptionBillPreview;
import form.user.FormPreviewUsers;
import form.user.FormUser;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import session.Session;

/**
 *
 * @author kicnilec
 */
public class FormMain extends javax.swing.JFrame {
    
    private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    
    public FormMain() {
        initComponents();
        setLocation();
        setMaximize();
        populateUserInfo();
    }

    /**
     * Creates new form FormMain
     */
//    public FormMain(User user) {
//        initComponents();
//        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
//        welcome(user);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUser = new javax.swing.JPanel();
        labelFirstname = new javax.swing.JLabel();
        labeleLastname = new javax.swing.JLabel();
        labelDisplayFirstname = new javax.swing.JLabel();
        labelDisplayLastname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jmbMainMenu = new javax.swing.JMenuBar();
        jmProducts = new javax.swing.JMenu();
        jmiNewProduct = new javax.swing.JMenuItem();
        jmiSearchProduct = new javax.swing.JMenuItem();
        jmiStorage = new javax.swing.JMenuItem();
        jmManufactures = new javax.swing.JMenu();
        jmiNewManufacturer = new javax.swing.JMenuItem();
        jmiSearchManufacturer = new javax.swing.JMenuItem();
        jmRedeptionBill = new javax.swing.JMenu();
        jmiNewRedemptionBill = new javax.swing.JMenuItem();
        jmiUpdateRedemptionBill = new javax.swing.JMenuItem();
        jmUsers = new javax.swing.JMenu();
        jmiNewUser = new javax.swing.JMenuItem();
        jmiSearchUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poljoprivredna zadruga");

        panelUser.setBorder(javax.swing.BorderFactory.createTitledBorder("User info"));

        labelFirstname.setText("First name:");

        labeleLastname.setText("Last name:");

        jLabel1.setText("Username:");

        jLabel2.setText("Email:");

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addComponent(labeleLastname)
                        .addGap(18, 18, 18)
                        .addComponent(labelDisplayLastname))
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addComponent(labelFirstname)
                        .addGap(18, 18, 18)
                        .addComponent(labelDisplayFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblUsername))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstname)
                    .addComponent(labelDisplayFirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeleLastname)
                    .addComponent(labelDisplayLastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblEmail))
                .addGap(0, 347, Short.MAX_VALUE))
        );

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jmProducts.setText("Products");

        jmiNewProduct.setText("New");
        jmiNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewProductActionPerformed(evt);
            }
        });
        jmProducts.add(jmiNewProduct);

        jmiSearchProduct.setText("Search");
        jmiSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchProductActionPerformed(evt);
            }
        });
        jmProducts.add(jmiSearchProduct);

        jmiStorage.setText("Storage");
        jmiStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStorageActionPerformed(evt);
            }
        });
        jmProducts.add(jmiStorage);

        jmbMainMenu.add(jmProducts);

        jmManufactures.setText("Manufactures");

        jmiNewManufacturer.setText("New");
        jmiNewManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewManufacturerActionPerformed(evt);
            }
        });
        jmManufactures.add(jmiNewManufacturer);

        jmiSearchManufacturer.setText("Search");
        jmiSearchManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchManufacturerActionPerformed(evt);
            }
        });
        jmManufactures.add(jmiSearchManufacturer);

        jmbMainMenu.add(jmManufactures);

        jmRedeptionBill.setText("Redemption Bill");

        jmiNewRedemptionBill.setText("New");
        jmiNewRedemptionBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewRedemptionBillActionPerformed(evt);
            }
        });
        jmRedeptionBill.add(jmiNewRedemptionBill);

        jmiUpdateRedemptionBill.setText("Update");
        jmiUpdateRedemptionBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUpdateRedemptionBillActionPerformed(evt);
            }
        });
        jmRedeptionBill.add(jmiUpdateRedemptionBill);

        jmbMainMenu.add(jmRedeptionBill);

        jmUsers.setText("Users");

        jmiNewUser.setText("New");
        jmiNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewUserActionPerformed(evt);
            }
        });
        jmUsers.add(jmiNewUser);

        jmiSearchUser.setText("Preview");
        jmiSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSearchUserActionPerformed(evt);
            }
        });
        jmUsers.add(jmiSearchUser);

        jmbMainMenu.add(jmUsers);

        setJMenuBar(jmbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 774, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addComponent(panelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewProductActionPerformed
        JDialog formProduct = new FormProduct(this, true, FormMode.NEW);
        formProduct.setVisible(true);
    }//GEN-LAST:event_jmiNewProductActionPerformed

    private void jmiSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchProductActionPerformed
        JFrame formSearchProduct = new FormSearchProduct();
        formSearchProduct.setVisible(true);
    }//GEN-LAST:event_jmiSearchProductActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Log out", JOptionPane.YES_NO_CANCEL_OPTION);
        if (choice == 0) {
            Session.getInstance().setUser(null);
            this.dispose();
            JFrame formLogin = new FormLogin();
            formLogin.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jmiNewManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewManufacturerActionPerformed
        JDialog formNewManufacturer = new FormManufacturer(this, true, FormMode.NEW);
        formNewManufacturer.setVisible(true);
    }//GEN-LAST:event_jmiNewManufacturerActionPerformed

    private void jmiSearchManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchManufacturerActionPerformed
        JFrame formSearchManufacturer = new FormSearchManufacturer();
        formSearchManufacturer.setVisible(true);
    }//GEN-LAST:event_jmiSearchManufacturerActionPerformed

    private void jmiNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewUserActionPerformed
        JDialog formNewUser = new FormUser(this, true);
        formNewUser.setVisible(true);
    }//GEN-LAST:event_jmiNewUserActionPerformed

    private void jmiSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSearchUserActionPerformed
        JFrame formPreviewUsers = new FormPreviewUsers();
        formPreviewUsers.setVisible(true);
    }//GEN-LAST:event_jmiSearchUserActionPerformed

    private void jmiNewRedemptionBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewRedemptionBillActionPerformed
        JDialog formNewRedemptionBill = new FormRedemptionBill(this, true,FormMode.NEW);
        formNewRedemptionBill.setVisible(true);
    }//GEN-LAST:event_jmiNewRedemptionBillActionPerformed

    private void jmiUpdateRedemptionBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUpdateRedemptionBillActionPerformed
        JFrame formPreviewRedemptionBill = new FormRedemptionBillPreview();
        formPreviewRedemptionBill.setVisible(true);
    }//GEN-LAST:event_jmiUpdateRedemptionBillActionPerformed

    private void jmiStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStorageActionPerformed
        JDialog formProductStorage = new FormProductStorage(this, true);
        formProductStorage.setVisible(true);
    }//GEN-LAST:event_jmiStorageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jmManufactures;
    private javax.swing.JMenu jmProducts;
    private javax.swing.JMenu jmRedeptionBill;
    private javax.swing.JMenu jmUsers;
    private javax.swing.JMenuBar jmbMainMenu;
    private javax.swing.JMenuItem jmiNewManufacturer;
    private javax.swing.JMenuItem jmiNewProduct;
    private javax.swing.JMenuItem jmiNewRedemptionBill;
    private javax.swing.JMenuItem jmiNewUser;
    private javax.swing.JMenuItem jmiSearchManufacturer;
    private javax.swing.JMenuItem jmiSearchProduct;
    private javax.swing.JMenuItem jmiSearchUser;
    private javax.swing.JMenuItem jmiStorage;
    private javax.swing.JMenuItem jmiUpdateRedemptionBill;
    private javax.swing.JLabel labelDisplayFirstname;
    private javax.swing.JLabel labelDisplayLastname;
    private javax.swing.JLabel labelFirstname;
    private javax.swing.JLabel labeleLastname;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelUser;
    // End of variables declaration//GEN-END:variables
    private void populateUserInfo() {
        User user = Session.getInstance().getUser();
        labelDisplayFirstname.setText(user.getFirstname());
        labelDisplayLastname.setText(user.getLastname());
        lblEmail.setText(user.getEmail());
        lblUsername.setText(user.getUsername());
    }
    
    private void setLocation() {
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }
    
    private void setMaximize() {
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }
}
