/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.manufacturer;

import controller.Controller;
import domain.Manufacturer;
import form.FormMode;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kicnilec
 */
public class FormManufacturer extends javax.swing.JDialog {

    /**
     * Creates new form FormManufacturer
     */
    public FormManufacturer(java.awt.Frame parent, boolean modal, FormMode mode, Manufacturer manufacturer) {
        super(parent, modal);
        initComponents();

        populateForm(manufacturer);
        setCenter();
        adjustForm(mode);
    }

    public FormManufacturer(java.awt.Frame parent, boolean modal, FormMode mode) {
        super(parent, modal);
        initComponents();

        setCenter();
        adjustForm(mode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Manufacturer");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Manufacturer"));

        jLabel1.setText("Name:");

        jLabel2.setText("Address:");

        jLabel3.setText("Place:");

        lblID.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(lblID))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPlace)
                    .addComponent(txtAddress)
                    .addComponent(txtName)
                    .addComponent(txtID))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnCancel)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnCancel)
                            .addComponent(btnUpdate)
                            .addComponent(btnSave))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtName.getText().trim();
        String address = txtAddress.getText().trim();
        String place = txtPlace.getText().trim();

        if (name.isEmpty() || address.isEmpty() || place.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all information!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Manufacturer manufacturer = new Manufacturer(name, address, place);
            try {
                Controller.getInstance().addManufacturer(manufacturer);//                Logger.getLogger(FormManufacturer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FormManufacturer.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Manufacturer has been saved!", "Success", JOptionPane.INFORMATION_MESSAGE);
            int option = JOptionPane.showConfirmDialog(this, "Add one more manufacturer?", "Add New", JOptionPane.YES_NO_OPTION);
            if (option == 0) {
                txtName.setText("");
                txtAddress.setText("");
                txtPlace.setText("");
            } else {
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Manufacturer manufacturer = getManufacturerUpdate();//            Logger.getLogger(FormManufacturer.class.getName()).log(Level.SEVERE, null, ex);
        try {
            Controller.getInstance().updateManufacturer(manufacturer);
        } catch (Exception ex) {
            Logger.getLogger(FormManufacturer.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Manufacturer has been successfully updated!", "Success", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        adjustForm(FormMode.EDIT);
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPlace;
    // End of variables declaration//GEN-END:variables

    private void adjustForm(FormMode mode) {
        switch (mode) {
            case NEW:
                lblID.setVisible(false);
                txtID.setVisible(false);
                txtAddress.setEnabled(true);
                txtName.setEnabled(true);
                txtPlace.setEnabled(true);

                btnEdit.setVisible(false);
                btnUpdate.setVisible(false);
                btnSave.setVisible(true);

                clearForm();
                setTitle("New Manufacturer");
                break;
            case EDIT:
                txtID.setEnabled(false);
                txtAddress.setEnabled(true);
                txtName.setEnabled(true);
                txtPlace.setEnabled(true);

                btnEdit.setVisible(false);
                btnUpdate.setVisible(true);
                btnSave.setVisible(false);

                setTitle("Edit Manufacturer");
                break;
            case VIEW:
                txtID.setEnabled(false);
                txtAddress.setEnabled(false);
                txtName.setEnabled(false);
                txtPlace.setEnabled(false);

                btnEdit.setVisible(true);
                btnUpdate.setVisible(false);
                btnSave.setVisible(false);

                setTitle("View Manufacturer");
                break;
        }
    }

    private void clearForm() {
        txtID.setText("");
        txtAddress.setText("");
        txtName.setText("");
        txtPlace.setText("");
    }

    private void populateForm(Manufacturer manufacturer) {
        txtID.setText(String.valueOf(manufacturer.getId()));
        txtAddress.setText(manufacturer.getAddress());
        txtName.setText(manufacturer.getName());
        txtPlace.setText(manufacturer.getPlace());
    }

    private void setCenter() {
        this.setLocationRelativeTo(null);
    }

    private Manufacturer getManufacturerUpdate() {
        Long id = new Long(txtID.getText());
        String address = txtAddress.getText().trim();
        String name = txtName.getText().trim();
        String place = txtPlace.getText().trim();
        return new Manufacturer(id, name, address, place);
    }
}
